name: Deploy to Server

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths:
      - "src"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js 22
      uses: actions/setup-node@v3
      with:
        node-version: '22'

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm build

    - name: copy dist via ssh password
      uses: appleboy/scp-action@master
      with:
        host: ${{secrets.SERVER_HOST}}
        username: ${{secrets.SERVER_USER}}
        password: ${{secrets.SERVER_PASSWORD}}
        key: ${{secrets.SSH_PRIVATE_KEY}}
        port: 22
        source: "dist"
        target: ${{secrets.SERVER_PATH}}

#    - name: Vercel Action Deploy
#      uses: amondnet/vercel-action@v25
#      with:
#        github-token: ${{ secrets.GITHUB_TOKEN }}
#        vercel-token: ${{ secrets.VERCEL_TOKEN }}
#        vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
#        vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
#        vercel-flag-yes: true
