name: Deploy to Vercel

on:
  push:
    branches:
      - main  # 可以根据需要更改为你使用的主分支名称

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js 22
      uses: actions/setup-node@v3
      with:
        node-version: '22'  # 设置 Node.js 22 版本
    
    - name: Install pnpm
      run: |
        npm install -g pnpm  # 安装 pnpm
    
    - name: Install dependencies
      run: pnpm install  # 使用 pnpm 安装依赖

    - name: Build project
      run: pnpm run build  # 构建 Vite 项目

    - name: Vercel Action Deploy
      uses: amondnet/vercel-action@v20
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN }}  # 你需要设置 VERCEL_TOKEN 为 GitHub Secret
        vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}  # 你的 Vercel 组织 ID
        vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}  # 你的 Vercel 项目 ID
        vercel-flag-yes: true
